### PR TITLE
#161754551 Add comment update and edit history

### PR DESCRIPTION
**Pull request by TheoOkafor**
#### What does this PR do?
- Add update-comment and comment edit history functionality

#### Description of Task to be completed?
- Add update comment route
- Add functionality to store enable comment history

#### How should this be manually tested?
- git clone `https://github.com/andela/haven-ah-backend.git`.
- Install `node` if not installed.
- ensure that PostgreSQL is running on your local machine.
- run `npm install` to install the npm packages.
- run `npm test` to run the unit and integration tests.

To test on postman
- run `npm run start-dev`
- On postman run PUT `localhost:5000/api/articles/:slug/comments/:id` (set JWT token as`x-access-token` in header).

#### Any background context you want to provide?
"When a user sends the `PUT` request to edit their comment.
Then the new comment should be added and the old one kept for the user."

#### What are the relevant pivotal tracker stories?
#161754551

##### UPDATE Comments

Good Response:
screen shot 2018-11-07 at 1 41 33 pm

The CommentHistory Table
screen shot 2018-11-07 at 1 42 23 pm

Bad Request Response (when body is not included):
screen shot 2018-11-05 at 5 32 17 pm

Bad Request Response (when the comment is not found)
screen shot 2018-11-07 at 1 45 58 pm

### CODE REVIEW

**Comment by victor-nweze-deel** [comment]
Looks good. Nice work @TheoOkafor

**Comment by PriscillaSam** [comment]
This looks great @TheoOkafor . Well done 👍.

**Comment by TheoOkafor** [comment]
Thank you @ProfJigsaw and @PriscillaSam

**Review by seyi-adeleke — APPROVED** [review]

**Comment by seyi-adeleke** [comment]
👍

**Pull request merged**
