### PR TITLE
#161412030 Refactor application folder structure

### PR DESCRIPTION
**Pull request by PriscillaSam**
#### What does this PR do?
Restructure folders and files to follow agreed file structure convention.

#### Description of tasks to be completed
- move folders into a server parent folder
- move files into appropriate folders
- remove package-lock.json file from files being tracked

#### How can this be manually tested?
Clone the repo and checkout to the `ch-refactor-file-structure-161412030` branch on your local machine.
The updated folder structure can be seen from the text editor.

#### What are the relevant Pivotal Tracker stories
#161412030

### CODE REVIEW

**Review by seyi-adeleke — COMMENTED** [review]
Lets have folders for tests and utilities

**Review by seyi-adeleke — COMMENTED** [review]
why did you remove the package-lock?

**Comment by PriscillaSam** [comment]
@seyi-adeleke 
To create those folders I'd need to already add a file in them because git doesn't track empty folders.

I removed the package-lock.json file because we don't have need of it on the remote repository. The moment the repo is cloned, all we need to do is run `npm install` and it would generate a new package-lock.json file.

**Update**:  I just read that indeed this file should be committed to the repository so that teammates, deployments, and continuous integration tools are guaranteed to install exactly the same dependencies when we run npm install.

**Comment by seyi-adeleke** [comment]
@PriscillaSam We need the package.lock in the repo to guarantee the integrity of our packages. Also you can add a file called `.gitkeep` to the folder to check it into source control. so something like `server/tests/.gitkeep`

**Review by seyi-adeleke — APPROVED** [review]

**Pull request merged**
